name: DifferentTreasure
description: A straight-forward, slimmed down treasure plugin.
main: me.hqm.different.treasure.DifferentTreasurePlugin
version: ${project.version}
author: HmmmQuestionMark
depend: [WorldGuard]
commands:
  treasure:
    usage: /<command [reload]
    aliases: [tr, dtr, differenttreasure]
permissions:
  different.treasure.info:
    default: true
    description: View the plugin info.
  different.treasure.reload:
    default: op
    description: Reload the plugin.