name: Treasures
description: A straight-forward, slimmed down treasure plugin.
main: me.hqm.treasures.TreasuresPlugin
version: ${project.version}
author: HmmmQuestionMark
depend: [WorldGuard]
commands:
  treasures:
    usage: /<command>
    aliases: [tr]
permissions:
  treasures.info:
    default: true
    description: View the plugin info.
  treasures.reload:
    default: op
    description: Reload the plugin.